<?php

namespace App\Services;

use App\Models\RuleDefinition;
use App\Models\Student;
use App\Models\StudentDevice;
use App\Models\StudentSetting;
use App\Models\TaskSession;
use App\Models\Violation;
use Carbon\CarbonInterface;
use Illuminate\Support\Facades\DB;

class AttentionTrackingViolationService
{
    private const RULE_TITLE = 'Look away';
    private const AUTO_KEY_PREFIX = 'look-away:';
    public function __construct(
        private readonly StudentPushUpCounterService $studentPushUpCounterService,
        private readonly TaskSessionUnfinishService $taskSessionUnfinishService,
        private readonly SpeechAnnouncementService $speechAnnouncementService,
        private readonly StudentAttentionStateService $studentAttentionStateService,
    ) {
    }

    public function recordLookAwayEvent(StudentDevice $device, ?CarbonInterface $occurredAt = null, array $payload = []): array
    {
        $occurredAt ??= now();

        return DB::transaction(function () use ($device, $occurredAt, $payload) {
            $lockedDevice = StudentDevice::query()
                ->with('student')
                ->whereKey($device->id)
                ->lockForUpdate()
                ->firstOrFail();

            $student = $lockedDevice->student;
            $activeTaskSession = TaskSession::query()
                ->where('student_id', $student->id)
                ->where('status', 'active')
                ->latest('started_at')
                ->lockForUpdate()
                ->first();

            if (! $activeTaskSession) {
                $this->resetLookAwayCountForStudent($student);

                return [
                    'accepted' => true,
                    'triggered_violation' => false,
                    'count' => 0,
                    'threshold' => $this->studentAttentionStateService->ensureSetting($student)->look_away_event_threshold,
                    'reason' => 'no_active_task',
                ];
            }

            $setting = $this->lockSetting($student);

            if ((int) ($setting->look_away_task_session_id ?? 0) !== $activeTaskSession->id) {
                $setting->forceFill([
                    'look_away_event_count' => 0,
                    'look_away_task_session_id' => $activeTaskSession->id,
                ])->save();
            }

            $count = (int) $setting->look_away_event_count + 1;
            $threshold = max(1, (int) ($setting->look_away_event_threshold ?? StudentAttentionStateService::DEFAULT_LOOK_AWAY_THRESHOLD));
            $autoGeneratedKey = self::AUTO_KEY_PREFIX.'task-session:'.$activeTaskSession->id;

            $existingViolation = Violation::query()
                ->where('auto_generated_key', $autoGeneratedKey)
                ->lockForUpdate()
                ->first();

            if ($existingViolation) {
                $setting->forceFill([
                    'look_away_event_count' => 0,
                    'look_away_task_session_id' => null,
                ])->save();

                return [
                    'accepted' => true,
                    'triggered_violation' => false,
                    'count' => 0,
                    'threshold' => $threshold,
                    'reason' => 'violation_already_open',
                ];
            }

            if ($count < $threshold) {
                $setting->forceFill([
                    'look_away_event_count' => $count,
                    'look_away_task_session_id' => $activeTaskSession->id,
                ])->save();

                return [
                    'accepted' => true,
                    'triggered_violation' => false,
                    'count' => $count,
                    'threshold' => $threshold,
                    'reason' => 'threshold_not_reached',
                ];
            }

            $ruleDefinition = $this->lookAwayRule();

            if (! $ruleDefinition) {
                $setting->forceFill([
                    'look_away_event_count' => $count,
                    'look_away_task_session_id' => $activeTaskSession->id,
                ])->save();

                return [
                    'accepted' => true,
                    'triggered_violation' => false,
                    'count' => $count,
                    'threshold' => $threshold,
                    'reason' => 'missing_rule_definition',
                ];
            }

            $notes = collect([
                'Automatic violation after repeated attention loss during the active task.',
                isset($payload['reason']) ? 'Reason: '.(string) $payload['reason'] : null,
                isset($payload['score']) ? 'Score: '.(string) $payload['score'] : null,
                isset($payload['away_seconds']) ? 'Away seconds: '.(string) $payload['away_seconds'] : null,
                'Task session: '.$activeTaskSession->task_title_snapshot,
            ])->filter()->implode(' ');

            $pushUpCount = $this->studentPushUpCounterService->allocateForViolation($student);

            $violation = Violation::create([
                'student_id' => $student->id,
                'rule_definition_id' => $ruleDefinition->id,
                'status' => 'open',
                'rule_title_snapshot' => $ruleDefinition->title,
                'penalty_units' => $pushUpCount,
                'occurred_at' => $occurredAt,
                'auto_generated_key' => $autoGeneratedKey,
                'notes' => $notes,
                'reported_by_user_id' => null,
            ]);

            $this->taskSessionUnfinishService->interruptActiveTaskForStudent($student, null);
            $this->studentAttentionStateService->resetLookAwayCountForStudent($student);
            $this->speechAnnouncementService->queueViolation($violation);

            return [
                'accepted' => true,
                'triggered_violation' => true,
                'count' => 0,
                'threshold' => $threshold,
                'violation_id' => $violation->id,
                'reason' => 'violation_created',
            ];
        });
    }

    public function recordLookAwayEventForStudent(Student $student, ?CarbonInterface $occurredAt = null, array $payload = []): array
    {
        $occurredAt ??= now();

        return DB::transaction(function () use ($student, $occurredAt, $payload) {
            $lockedStudent = Student::query()
                ->whereKey($student->id)
                ->lockForUpdate()
                ->firstOrFail();

            return $this->recordLookAwayForLockedStudent($lockedStudent, $occurredAt, $payload);
        });
    }

    public function resetLookAwayCountForStudent(Student $student): void
    {
        $this->studentAttentionStateService->resetLookAwayCountForStudent($student);
    }

    private function lockSetting(Student $student): StudentSetting
    {
        $this->studentAttentionStateService->ensureSetting($student);

        return StudentSetting::query()
            ->where('student_id', $student->id)
            ->lockForUpdate()
            ->firstOrFail();
    }

    private function lookAwayRule(): ?RuleDefinition
    {
        return RuleDefinition::query()
            ->where('title', self::RULE_TITLE)
            ->where('scope', 'global')
            ->whereNull('student_id')
            ->where('is_active', true)
            ->first();
    }

    private function recordLookAwayForLockedStudent(Student $student, CarbonInterface $occurredAt, array $payload): array
    {
        $activeTaskSession = TaskSession::query()
            ->where('student_id', $student->id)
            ->where('status', 'active')
            ->latest('started_at')
            ->lockForUpdate()
            ->first();

        if (! $activeTaskSession) {
            $this->studentAttentionStateService->resetLookAwayCountForStudent($student);

            return [
                'accepted' => true,
                'triggered_violation' => false,
                'count' => 0,
                'threshold' => $this->studentAttentionStateService->ensureSetting($student)->look_away_event_threshold,
                'reason' => 'no_active_task',
            ];
        }

        $setting = $this->lockSetting($student);

        if ((int) ($setting->look_away_task_session_id ?? 0) !== $activeTaskSession->id) {
            $setting->forceFill([
                'look_away_event_count' => 0,
                'look_away_task_session_id' => $activeTaskSession->id,
            ])->save();
        }

        $count = (int) $setting->look_away_event_count + 1;
        $threshold = max(1, (int) ($setting->look_away_event_threshold ?? StudentAttentionStateService::DEFAULT_LOOK_AWAY_THRESHOLD));
        $autoGeneratedKey = self::AUTO_KEY_PREFIX.'task-session:'.$activeTaskSession->id;

        $existingViolation = Violation::query()
            ->where('auto_generated_key', $autoGeneratedKey)
            ->lockForUpdate()
            ->first();

        if ($existingViolation) {
            $setting->forceFill([
                'look_away_event_count' => 0,
                'look_away_task_session_id' => null,
            ])->save();

            return [
                'accepted' => true,
                'triggered_violation' => false,
                'count' => 0,
                'threshold' => $threshold,
                'reason' => 'violation_already_open',
            ];
        }

        if ($count < $threshold) {
            $setting->forceFill([
                'look_away_event_count' => $count,
                'look_away_task_session_id' => $activeTaskSession->id,
            ])->save();

            return [
                'accepted' => true,
                'triggered_violation' => false,
                'count' => $count,
                'threshold' => $threshold,
                'reason' => 'threshold_not_reached',
            ];
        }

        $ruleDefinition = $this->lookAwayRule();

        if (! $ruleDefinition) {
            $setting->forceFill([
                'look_away_event_count' => $count,
                'look_away_task_session_id' => $activeTaskSession->id,
            ])->save();

            return [
                'accepted' => true,
                'triggered_violation' => false,
                'count' => $count,
                'threshold' => $threshold,
                'reason' => 'missing_rule_definition',
            ];
        }

        $notes = collect([
            'Automatic violation after repeated attention loss during the active task.',
            isset($payload['reason']) ? 'Reason: '.(string) $payload['reason'] : null,
            isset($payload['score']) ? 'Score: '.(string) $payload['score'] : null,
            isset($payload['away_seconds']) ? 'Away seconds: '.(string) $payload['away_seconds'] : null,
            'Task session: '.$activeTaskSession->task_title_snapshot,
        ])->filter()->implode(' ');

        $pushUpCount = $this->studentPushUpCounterService->allocateForViolation($student);

        $violation = Violation::create([
            'student_id' => $student->id,
            'rule_definition_id' => $ruleDefinition->id,
            'status' => 'open',
            'rule_title_snapshot' => $ruleDefinition->title,
            'penalty_units' => $pushUpCount,
            'occurred_at' => $occurredAt,
            'auto_generated_key' => $autoGeneratedKey,
            'notes' => $notes,
            'reported_by_user_id' => null,
        ]);

        $this->taskSessionUnfinishService->interruptActiveTaskForStudent($student, null);
        $this->studentAttentionStateService->resetLookAwayCountForStudent($student);
        $this->speechAnnouncementService->queueViolation($violation);

        return [
            'accepted' => true,
            'triggered_violation' => true,
            'count' => 0,
            'threshold' => $threshold,
            'violation_id' => $violation->id,
            'reason' => 'violation_created',
        ];
    }
}
