<?php

namespace App\Services;

use App\Models\RuleDefinition;
use App\Models\Student;
use App\Models\StudentDevice;
use App\Models\StudentSetting;
use App\Models\TaskSession;
use App\Models\Violation;
use Carbon\CarbonInterface;
use Illuminate\Support\Facades\DB;

class AttentionTrackingViolationService
{
    private const RULE_TITLE = 'Look away';
    private const BODY_MISSING_RULE_TITLE = 'Left camera view';
    private const AUTO_KEY_PREFIX = 'look-away:';
    private const BODY_MISSING_AUTO_KEY_PREFIX = 'body-missing:';

    public function __construct(
        private readonly StudentPushUpCounterService $studentPushUpCounterService,
        private readonly TaskSessionUnfinishService $taskSessionUnfinishService,
        private readonly SpeechAnnouncementService $speechAnnouncementService,
        private readonly StudentAttentionStateService $studentAttentionStateService,
    ) {
    }

    public function recordLookAwayEvent(
        StudentDevice $device,
        ?CarbonInterface $occurredAt = null,
        array $payload = [],
        string $eventType = 'look_away',
    ): array {
        $occurredAt ??= now();

        return DB::transaction(function () use ($device, $occurredAt, $payload, $eventType) {
            $lockedDevice = StudentDevice::query()
                ->with('student')
                ->whereKey($device->id)
                ->lockForUpdate()
                ->firstOrFail();

            return $this->recordAttentionEventForLockedStudent($lockedDevice->student, $eventType, $occurredAt, $payload);
        });
    }

    public function recordLookAwayEventForStudent(
        Student $student,
        ?CarbonInterface $occurredAt = null,
        array $payload = [],
        string $eventType = 'look_away',
    ): array {
        $occurredAt ??= now();

        return DB::transaction(function () use ($student, $occurredAt, $payload, $eventType) {
            $lockedStudent = Student::query()
                ->whereKey($student->id)
                ->lockForUpdate()
                ->firstOrFail();

            return $this->recordAttentionEventForLockedStudent($lockedStudent, $eventType, $occurredAt, $payload);
        });
    }

    public function resetLookAwayCountForStudent(Student $student): void
    {
        $this->studentAttentionStateService->resetLookAwayCountForStudent($student);
    }

    private function lockSetting(Student $student): StudentSetting
    {
        $this->studentAttentionStateService->ensureSetting($student);

        return StudentSetting::query()
            ->where('student_id', $student->id)
            ->lockForUpdate()
            ->firstOrFail();
    }

    private function lookAwayRule(): ?RuleDefinition
    {
        return RuleDefinition::query()
            ->where('title', self::RULE_TITLE)
            ->where('scope', 'global')
            ->whereNull('student_id')
            ->where('is_active', true)
            ->first();
    }

    private function bodyMissingRule(): ?RuleDefinition
    {
        return RuleDefinition::query()
            ->where('title', self::BODY_MISSING_RULE_TITLE)
            ->where('scope', 'global')
            ->whereNull('student_id')
            ->where('is_active', true)
            ->first() ?? $this->lookAwayRule();
    }

    private function recordAttentionEventForLockedStudent(
        Student $student,
        string $eventType,
        CarbonInterface $occurredAt,
        array $payload,
    ): array {
        if ($eventType === 'body_missing') {
            return $this->recordBodyMissingForLockedStudent($student, $occurredAt, $payload);
        }

        return $this->recordLookAwayForLockedStudent($student, $occurredAt, $payload);
    }

    private function recordLookAwayForLockedStudent(Student $student, CarbonInterface $occurredAt, array $payload): array
    {
        $activeTaskSession = $this->lockedActiveTaskSessionForStudent($student);

        if (! $activeTaskSession) {
            $this->studentAttentionStateService->resetLookAwayCountForStudent($student);

            return [
                'accepted' => true,
                'triggered_violation' => false,
                'count' => 0,
                'threshold' => $this->studentAttentionStateService->ensureSetting($student)->look_away_event_threshold,
                'reason' => 'no_active_task',
            ];
        }

        $setting = $this->lockSetting($student);

        if ((int) ($setting->look_away_task_session_id ?? 0) !== $activeTaskSession->id) {
            $setting->forceFill([
                'look_away_event_count' => 0,
                'look_away_task_session_id' => $activeTaskSession->id,
            ])->save();
        }

        $count = (int) $setting->look_away_event_count + 1;
        $threshold = max(1, (int) ($setting->look_away_event_threshold ?? StudentAttentionStateService::DEFAULT_LOOK_AWAY_THRESHOLD));
        $autoGeneratedKey = self::AUTO_KEY_PREFIX.'task-session:'.$activeTaskSession->id;

        $existingViolation = Violation::query()
            ->where('auto_generated_key', $autoGeneratedKey)
            ->lockForUpdate()
            ->first();

        if ($existingViolation) {
            $setting->forceFill([
                'look_away_event_count' => 0,
                'look_away_task_session_id' => null,
            ])->save();

            return [
                'accepted' => true,
                'triggered_violation' => false,
                'count' => 0,
                'threshold' => $threshold,
                'reason' => 'violation_already_open',
            ];
        }

        if ($count < $threshold) {
            $setting->forceFill([
                'look_away_event_count' => $count,
                'look_away_task_session_id' => $activeTaskSession->id,
            ])->save();

            return [
                'accepted' => true,
                'triggered_violation' => false,
                'count' => $count,
                'threshold' => $threshold,
                'reason' => 'threshold_not_reached',
            ];
        }

        $ruleDefinition = $this->lookAwayRule();

        if (! $ruleDefinition) {
            $setting->forceFill([
                'look_away_event_count' => $count,
                'look_away_task_session_id' => $activeTaskSession->id,
            ])->save();

            return [
                'accepted' => true,
                'triggered_violation' => false,
                'count' => $count,
                'threshold' => $threshold,
                'reason' => 'missing_rule_definition',
            ];
        }

        $violation = $this->createViolation(
            $student,
            $activeTaskSession,
            $ruleDefinition,
            $autoGeneratedKey,
            $occurredAt,
            collect([
                'Automatic violation after repeated attention loss during the active task.',
                isset($payload['reason']) ? 'Reason: '.(string) $payload['reason'] : null,
                isset($payload['score']) ? 'Score: '.(string) $payload['score'] : null,
                isset($payload['away_seconds']) ? 'Away seconds: '.(string) $payload['away_seconds'] : null,
                'Task session: '.$activeTaskSession->task_title_snapshot,
            ])->filter()->implode(' '),
        );

        $this->studentAttentionStateService->resetLookAwayCountForStudent($student);

        return [
            'accepted' => true,
            'triggered_violation' => true,
            'count' => 0,
            'threshold' => $threshold,
            'violation_id' => $violation->id,
            'reason' => 'violation_created',
        ];
    }

    private function recordBodyMissingForLockedStudent(Student $student, CarbonInterface $occurredAt, array $payload): array
    {
        $activeTaskSession = $this->lockedActiveTaskSessionForStudent($student);

        if (! $activeTaskSession) {
            $this->studentAttentionStateService->resetLookAwayCountForStudent($student);

            return [
                'accepted' => true,
                'triggered_violation' => false,
                'threshold_seconds' => $this->bodyMissingViolationSeconds(),
                'reason' => 'no_active_task',
            ];
        }

        $awaySeconds = (float) ($payload['away_seconds'] ?? 0);
        $thresholdSeconds = $this->bodyMissingViolationSeconds();

        if ($awaySeconds < $thresholdSeconds) {
            return [
                'accepted' => true,
                'triggered_violation' => false,
                'away_seconds' => $awaySeconds,
                'threshold_seconds' => $thresholdSeconds,
                'reason' => 'threshold_not_reached',
            ];
        }

        $autoGeneratedKey = self::BODY_MISSING_AUTO_KEY_PREFIX.'task-session:'.$activeTaskSession->id;
        $existingViolation = Violation::query()
            ->where('auto_generated_key', $autoGeneratedKey)
            ->lockForUpdate()
            ->first();

        if ($existingViolation) {
            return [
                'accepted' => true,
                'triggered_violation' => false,
                'away_seconds' => $awaySeconds,
                'threshold_seconds' => $thresholdSeconds,
                'reason' => 'violation_already_open',
            ];
        }

        $ruleDefinition = $this->bodyMissingRule();

        if (! $ruleDefinition) {
            return [
                'accepted' => true,
                'triggered_violation' => false,
                'away_seconds' => $awaySeconds,
                'threshold_seconds' => $thresholdSeconds,
                'reason' => 'missing_rule_definition',
            ];
        }

        $violation = $this->createViolation(
            $student,
            $activeTaskSession,
            $ruleDefinition,
            $autoGeneratedKey,
            $occurredAt,
            collect([
                'Automatic violation after the student left the camera view during the active task.',
                'Away seconds: '.(string) round($awaySeconds, 1),
                isset($payload['reason']) ? 'Reason: '.(string) $payload['reason'] : null,
                isset($payload['score']) ? 'Score: '.(string) $payload['score'] : null,
                isset($payload['body_confidence']) ? 'Body confidence: '.(string) $payload['body_confidence'] : null,
                'Task session: '.$activeTaskSession->task_title_snapshot,
            ])->filter()->implode(' '),
        );

        $this->studentAttentionStateService->resetLookAwayCountForStudent($student);

        return [
            'accepted' => true,
            'triggered_violation' => true,
            'away_seconds' => $awaySeconds,
            'threshold_seconds' => $thresholdSeconds,
            'violation_id' => $violation->id,
            'reason' => 'violation_created',
        ];
    }

    private function lockedActiveTaskSessionForStudent(Student $student): ?TaskSession
    {
        return TaskSession::query()
            ->where('student_id', $student->id)
            ->where('status', 'active')
            ->latest('started_at')
            ->lockForUpdate()
            ->first();
    }

    private function createViolation(
        Student $student,
        TaskSession $activeTaskSession,
        RuleDefinition $ruleDefinition,
        string $autoGeneratedKey,
        CarbonInterface $occurredAt,
        string $notes,
    ): Violation {
        $pushUpCount = $this->studentPushUpCounterService->allocateForViolation($student);

        $violation = Violation::create([
            'student_id' => $student->id,
            'rule_definition_id' => $ruleDefinition->id,
            'status' => 'open',
            'rule_title_snapshot' => $ruleDefinition->title,
            'penalty_units' => $pushUpCount,
            'occurred_at' => $occurredAt,
            'auto_generated_key' => $autoGeneratedKey,
            'notes' => $notes,
            'reported_by_user_id' => null,
        ]);

        $this->taskSessionUnfinishService->interruptActiveTaskForStudent($student, null);
        $this->speechAnnouncementService->queueViolation($violation);

        return $violation;
    }

    private function bodyMissingViolationSeconds(): float
    {
        return max(1.0, (float) config('services.attention_tracking.body_missing_violation_seconds', 10));
    }
}
