<?php

namespace App\Services;

use App\Models\BrowserVisitLog;
use App\Models\DeviceActivityEvent;
use App\Models\RuleDefinition;
use App\Models\Student;
use App\Models\StudentAppPolicy;
use App\Models\StudentDevice;
use App\Models\TaskSession;
use App\Models\User;
use App\Models\Violation;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class BlockedResourceViolationService
{
    public const BLOCKED_PROGRAM_RULE_TITLE = 'Blocked program opened';

    public const BLOCKED_WEBSITE_RULE_TITLE = 'Blocked website opened';

    public function __construct(
        private readonly StudentPushUpCounterService $pushUpCounterService,
        private readonly ActivityLogService $activityLogService,
    ) {}

    public function recordBlockedProgramOpened(
        StudentDevice $device,
        StudentAppPolicy $policy,
        array $app,
        ?DeviceActivityEvent $event = null,
        ?TaskSession $activeTaskSession = null,
    ): ?Violation {
        $student = $device->student()->firstOrFail();
        $appName = trim((string) ($app['app_name'] ?? $policy->app_name));
        $scope = $policy->task_template_id ? 'task-template:'.$policy->task_template_id : 'global';
        $dedupePrefix = 'blocked-resource:app:student:'.$student->id.':policy:'.$policy->id;
        $autoGeneratedKey = $dedupePrefix.':event:'.($event?->id ?? now()->format('YmdHis'));

        $taskDescription = $activeTaskSession
            ? ' during task '.$activeTaskSession->task_title_snapshot
            : '';

        $violation = $this->createViolationIfNoOpenMatch(
            $student,
            self::BLOCKED_PROGRAM_RULE_TITLE,
            $dedupePrefix,
            $autoGeneratedKey,
            'Automatic violation for opening blocked program '.$appName.$taskDescription.'. Scope: '.$scope.'.',
        );

        if ($violation) {
            $this->activityLogService->log(
                'apps',
                'blocked_program_violation',
                'Blocked program violation: '.$appName,
                $student->id,
                null,
                $violation,
                [
                    'app_name' => $appName,
                    'scope' => $scope,
                    'student_device_id' => $device->id,
                    'student_app_policy_id' => $policy->id,
                    'device_activity_event_id' => $event?->id,
                    'task_session_id' => $activeTaskSession?->id,
                    'task_title' => $activeTaskSession?->task_title_snapshot,
                    'violation_id' => $violation->id,
                ],
            );
        }

        return $violation;
    }

    public function recordBlockedWebsiteVisit(BrowserVisitLog $visit): ?Violation
    {
        if ($visit->decision !== 'blocked') {
            return null;
        }

        if (($visit->meta['source'] ?? null) !== 'explicit_navigation') {
            return null;
        }

        $visit->loadMissing(['student', 'matchedRule']);
        $student = $visit->student;

        if (! $student) {
            return null;
        }

        $activeTaskSession = $this->activeTaskSession($student);
        $domain = $visit->registrable_domain ?: $visit->host ?: 'unknown';
        $scope = $visit->matchedRule?->task_template_id
            ? 'task-template:'.$visit->matchedRule->task_template_id
            : ($activeTaskSession?->task_template_id ? 'task-template:'.$activeTaskSession->task_template_id : 'global');
        $rulePart = $visit->matched_rule_id ? 'rule:'.$visit->matched_rule_id : 'rule:none';
        $dedupePrefix = 'blocked-resource:website:student:'.$student->id
            .':'.substr(hash('sha256', $domain.'|'.$visit->mode.'|'.$scope.'|'.$rulePart), 0, 24);
        $autoGeneratedKey = $dedupePrefix.':visit:'.$visit->id;

        $taskDescription = $activeTaskSession
            ? ' during task '.$activeTaskSession->task_title_snapshot
            : '';

        $violation = $this->createViolationIfNoOpenMatch(
            $student,
            self::BLOCKED_WEBSITE_RULE_TITLE,
            $dedupePrefix,
            $autoGeneratedKey,
            'Automatic violation for opening blocked website '.$domain.$taskDescription.'. URL: '
                .Str::limit($visit->url, 500, '').'.',
        );

        if ($violation) {
            $this->activityLogService->log(
                'websites',
                'blocked_website_violation',
                'Blocked website violation: '.$domain,
                $student->id,
                null,
                $violation,
                [
                    'url' => $visit->url,
                    'host' => $visit->host,
                    'registrable_domain' => $visit->registrable_domain,
                    'domain' => $domain,
                    'mode' => $visit->mode,
                    'scope' => $scope,
                    'source' => $visit->meta['source'] ?? null,
                    'matched_rule_id' => $visit->matched_rule_id,
                    'browser_visit_log_id' => $visit->id,
                    'student_device_id' => $visit->student_device_id,
                    'task_session_id' => $activeTaskSession?->id,
                    'task_title' => $activeTaskSession?->task_title_snapshot,
                    'violation_id' => $violation->id,
                ],
            );
        }

        return $violation;
    }

    private function createViolationIfNoOpenMatch(
        Student $student,
        string $ruleTitle,
        string $dedupePrefix,
        string $autoGeneratedKey,
        string $notes,
    ): ?Violation {
        $ruleDefinition = $this->ruleDefinition($student, $ruleTitle);

        if (! $ruleDefinition) {
            return null;
        }

        return DB::transaction(function () use ($student, $ruleDefinition, $dedupePrefix, $autoGeneratedKey, $notes) {
            Student::query()
                ->whereKey($student->id)
                ->lockForUpdate()
                ->first();

            $existingOpenViolation = Violation::query()
                ->where('student_id', $student->id)
                ->where('status', 'open')
                ->where('auto_generated_key', 'like', $dedupePrefix.':%')
                ->lockForUpdate()
                ->first();

            if ($existingOpenViolation) {
                return null;
            }

            if (Violation::query()->where('auto_generated_key', $autoGeneratedKey)->exists()) {
                return null;
            }

            $pushUpCount = $this->pushUpCounterService->allocateForViolation($student);

            return Violation::create([
                'student_id' => $student->id,
                'rule_definition_id' => $ruleDefinition->id,
                'status' => 'open',
                'rule_title_snapshot' => $ruleDefinition->title,
                'penalty_units' => $pushUpCount,
                'occurred_at' => now(),
                'notes' => $notes,
                'reported_by_user_id' => null,
                'auto_generated_key' => $autoGeneratedKey,
            ]);
        });
    }

    private function ruleDefinition(Student $student, string $title): ?RuleDefinition
    {
        $existing = RuleDefinition::query()
            ->where('title', $title)
            ->where('scope', 'global')
            ->whereNull('student_id')
            ->first();

        if ($existing) {
            if (! $existing->is_active) {
                return null;
            }

            return $existing;
        }

        $creatorId = $student->user_id ?: User::query()->orderBy('id')->value('id');

        if (! $creatorId) {
            return null;
        }

        return RuleDefinition::create([
            'title' => $title,
            'description' => 'Automatic violation preset: '.$title.'.',
            'scope' => 'global',
            'student_id' => null,
            'default_penalty_units' => 50,
            'is_active' => true,
            'created_by_user_id' => $creatorId,
        ]);
    }

    private function activeTaskSession(Student $student): ?TaskSession
    {
        return $student->taskSessions()
            ->where('status', 'active')
            ->latest('started_at')
            ->latest('id')
            ->first();
    }
}
